build:
  image:
    name: pandoc/extra:edge-ubuntu
    entrypoint: [""]
  script:
    - mkdir public
    - /usr/local/bin/pandoc --from gfm --to html --standalone -o ./public/index.html ./README.md
  artifacts:
    paths:
      - public
  pages: true
