---
build:
  image:
    name: pandoc/extra:edge-ubuntu
    entrypoint: [""]
  script:
    - mkdir output
    - /usr/local/bin/pandoc --from gfm --to html --standalone -o ./output/index.html ./README.md
  artifacts:
    paths:
      - output
  pages: true
  publish: output
