name: GitHub CI pipeline

on:
  push:
    branches: ["*"]

jobs:
  Build_with_Docker:
    runs-on: ubuntu-latest
    container:
      image: pandoc/extra:edge-ubuntu
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir ./output
          /usr/local/bin/pandoc --from gfm --to html --standalone -o ./output/index.html ./README.md
